#!/bin/bash

set -xe

# install dependencies
juju-log "Install Ubuntu 14.04 packages"
# TODO: Use Postgresql Charm and not internally!
apt-get install -y git python-virtualenv libpq-dev postgresql-client python-dev swig libssl-dev libjpeg-dev redis-server nginx
# install pybossa itself
juju-log "Clone PyBossa Git in home directory"
cd ~
git clone --recursive https://github.com/PyBossa/pybossa
cd pybossa
juju-log "Install Python dependencies"
pip install -r requirements.txt
juju-log "Use default settings for PyBossa"
cp settings_local.py.tmpl settings_local.py
cp alembic.ini.template alembic.ini
juju-log "Install requirements for letting run PyBossa as a service"
pip install supervisor