#!/bin/sh
set -ex # -x for verbose logging to juju debug-log

juju-log $JUJU_REMOTE_UNIT joined

# db-relation-joined example
juju-log "Joining database at $JUJU_REMOTE_UNIT"
hostname=`unit-get public-address`
juju-log "from host: $hostname"
# Check to see if 'database' has been set, and loop until it is
database=`relation-get database`
if [ -z "$database" ] ; then
   exit 0
fi
# retrieve the remaining values which have been set by the mysql charm
user=`relation-get user`
password=`relation-get password`
host=`relation-get private-address`
slave=`relation-get slave`
# do something with these values
juju-log "Database acquired"
juju-log "database: $database username: $user host: $host"
