#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'

cd ~/pybossa
if [ -f ".psql" ]; then
  juju-log "Trying to (re)start pybossa"
  redis-server contrib/sentinel.conf --sentinel
  export PYBOSSA_REDIS_CACHE_DISABLED='1'
  supervisorctl restart pybossa || supervisorctl start pybossa
  juju-log "Pybossa should be running now on port 8080 (nginx) internally"
else
  juju-log "No database set up yet, waiting."
fi
