#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'

cd ~/pybossa
redis-server contrib/sentinel.conf --sentinel
export PYBOSSA_REDIS_CACHE_DISABLED='1'
python run.py